#!/usr/bin/env bash
#
# Optional. Upgrades country artwork from emoji to the flag-icons SVG set.
#
# The app ships working without this: Countries derives emoji from the ISO
# code, so every country has artwork with nothing bundled. Emoji are drawn by
# the system font though, which means Apple's design rather than ours, no
# control over detail at complication size, and nothing at all for regions the
# font omits. This swaps in real vector artwork.
#
# Xcode asset catalogs have taken SVG directly since Xcode 12, so no
# rasterising tool is needed - the SVGs go in as-is.
#
# The catalogue lives in Assets/ and is a member of all four targets rather
# than a Swift package resource. As an SPM resource, Image(_:bundle: .module)
# rendered nothing inside a widget extension even though the catalogue was
# present, which left the watch complication blank.
#
# flag-icons is MIT. Its LICENSE is copied into the catalog so the notice
# ships with the artwork, which MIT requires.
#
# Usage: Tools/fetch-flags.sh [version]

set -euo pipefail

VERSION="${1:-7.5.0}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CATALOG="$ROOT/Assets/Flags.xcassets"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "Fetching lipis/flag-icons $VERSION"
curl -fsSL "https://github.com/lipis/flag-icons/archive/refs/tags/v${VERSION}.tar.gz" \
  | tar xz -C "$WORK"
SRC="$WORK/flag-icons-${VERSION}"

# 1x1 rather than 4x3: complication slots are circular, and a square source
# survives a circular clip without losing the flag's centre.
if [ ! -d "$SRC/flags/1x1" ]; then
  echo "error: no flags/1x1 in the downloaded archive" >&2
  exit 1
fi

rm -rf "$CATALOG"
mkdir -p "$CATALOG"
printf '{"info":{"author":"xcode","version":1}}\n' > "$CATALOG/Contents.json"

# Beside the catalog, not inside it: asset catalogs compile to Assets.car and
# drop anything they do not recognise, so a .txt in there never reaches the
# built product. MIT wants the notice shipped with the artwork.
cp "$SRC/LICENSE" "$(dirname "$CATALOG")/flag-icons-LICENSE.txt"

count=0
for svg in "$SRC"/flags/1x1/*.svg; do
  code="$(basename "$svg" .svg)"
  # Skip anything that is not a two-letter ISO 3166-1 alpha-2 code; the set
  # also carries subdivisions like gb-eng that Countries does not list.
  [[ "$code" =~ ^[a-z]{2}$ ]] || continue
  set="$CATALOG/flag-$code.imageset"
  mkdir -p "$set"

  # These carry a 512 viewBox and no width/height, so Xcode rasterises at 512,
  # 1024 and 1536. Across 257 flags that is 7.8MB of Assets.car, duplicated
  # into every extension that links FlagKit. Capping the intrinsic size at 160
  # brings it to 2.6MB and still covers the largest use: an iOS systemSmall
  # widget at 3x needs ~474px, and 160 x 3 is 480. The watch never asks for
  # more than ~110px.
  sed 's|<svg |<svg width="160" height="160" |' "$svg" > "$set/flag-$code.svg"
  # No preserves-vector-representation: it made no measurable size difference
  # and we never draw these larger than the capped raster covers.
  cat > "$set/Contents.json" <<JSON
{
  "images" : [
    {
      "filename" : "flag-$code.svg",
      "idiom" : "universal"
    }
  ],
  "info" : { "author" : "xcode", "version" : 1 }
}
JSON
  count=$((count + 1))
done

# Tell FlagKit which codes actually have artwork, so Countries can prefer an
# asset and fall back to emoji for anything missing.
GEN="$ROOT/Packages/FlagKit/Sources/FlagKit/CountryAssets.swift"
{
  echo "// Generated by Tools/fetch-flags.sh from lipis/flag-icons $VERSION."
  echo "// Do not edit by hand."
  echo
  echo "enum CountryAssets {"
  echo "    static let available: Set<String> = ["
  for set in "$CATALOG"/flag-*.imageset; do
    code="$(basename "$set" .imageset)"
    echo "        \"${code#flag-}\","
  done
  echo "    ]"
  echo "}"
} > "$GEN"

echo "Wrote $count flags to $CATALOG"
echo "Run: swift test --package-path Packages/FlagKit"
