#!/usr/bin/env bash
#
# Optional. Upgrades country artwork from emoji to the flag-icons SVG set.
#
# The app ships working without this: Countries derives emoji from the ISO
# code, so every country has artwork with nothing bundled. Emoji are drawn by
# the system font though, which means Apple's design rather than ours, no
# control over detail at complication size, and nothing at all for regions the
# font omits. This swaps in real vector artwork.
#
# Xcode asset catalogs have taken SVG directly since Xcode 12, so no
# rasterising tool is needed - the SVGs go in as-is.
#
# flag-icons is MIT. Its LICENSE is copied into the catalog so the notice
# ships with the artwork, which MIT requires.
#
# Usage: Tools/fetch-flags.sh [version]

set -euo pipefail

VERSION="${1:-7.2.3}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CATALOG="$ROOT/Packages/FlagKit/Sources/FlagKit/Resources/Flags.xcassets"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "Fetching lipis/flag-icons $VERSION"
curl -fsSL "https://github.com/lipis/flag-icons/archive/refs/tags/v${VERSION}.tar.gz" \
  | tar xz -C "$WORK"
SRC="$WORK/flag-icons-${VERSION}"

# 1x1 rather than 4x3: complication slots are circular, and a square source
# survives a circular clip without losing the flag's centre.
if [ ! -d "$SRC/flags/1x1" ]; then
  echo "error: no flags/1x1 in the downloaded archive" >&2
  exit 1
fi

rm -rf "$CATALOG"
mkdir -p "$CATALOG"
printf '{"info":{"author":"xcode","version":1}}\n' > "$CATALOG/Contents.json"
cp "$SRC/LICENSE" "$CATALOG/flag-icons-LICENSE.txt"

count=0
for svg in "$SRC"/flags/1x1/*.svg; do
  code="$(basename "$svg" .svg)"
  # Skip anything that is not a two-letter ISO 3166-1 alpha-2 code; the set
  # also carries subdivisions like gb-eng that Countries does not list.
  [[ "$code" =~ ^[a-z]{2}$ ]] || continue
  set="$CATALOG/flag-$code.imageset"
  mkdir -p "$set"
  cp "$svg" "$set/flag-$code.svg"
  cat > "$set/Contents.json" <<JSON
{
  "images" : [
    {
      "filename" : "flag-$code.svg",
      "idiom" : "universal"
    }
  ],
  "info" : { "author" : "xcode", "version" : 1 },
  "properties" : { "preserves-vector-representation" : true }
}
JSON
  count=$((count + 1))
done

# Tell FlagKit which codes actually have artwork, so Countries can prefer an
# asset and fall back to emoji for anything missing.
GEN="$ROOT/Packages/FlagKit/Sources/FlagKit/CountryAssets.swift"
{
  echo "// Generated by Tools/fetch-flags.sh from lipis/flag-icons $VERSION."
  echo "// Do not edit by hand."
  echo
  echo "enum CountryAssets {"
  echo "    static let available: Set<String> = ["
  for set in "$CATALOG"/flag-*.imageset; do
    code="$(basename "$set" .imageset)"
    echo "        \"${code#flag-}\","
  done
  echo "    ]"
  echo "}"
} > "$GEN"

echo "Wrote $count flags to $CATALOG"
echo
echo "Remaining manual step: add the resource to Packages/FlagKit/Package.swift"
echo
echo '    .target(name: "FlagKit", resources: [.process("Resources")]),'
echo
echo "then have Countries use .asset when CountryAssets.available contains the code."
